"""Rack assemblies applied as construction units: assemble() replays them as one call."""

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from tuba import Model
from tuba.assemblies import RackBay, RackCorner, RackRow, assemble
from tuba.patches import ModelTransaction
from tuba.project import run_model_script
from tuba.project.script import same_model, write_model_script

BAY_PARAMS = dict(
    name="rack_A",
    origin=(0.0, 0.0, 0.0),
    length=4.0,
    width=1.0,
    height=3.0,
    levels=(1.5, 3.0),
    section="RackSec",
    material="Steel",
    zone="north",
)

ROW_PARAMS = dict(
    name_prefix="rack_A",
    origin=(-10.0, 0.0, -3.0),
    material="Steel",
    section="RackSec",
    direction="X",
    bays=2,
    bay_length=2.0,
    width=2.0,
    height=3.0,
    levels=(2.75,),
)


class TestAssemblyUnits(unittest.TestCase):
    def _model(self) -> Model:
        model = Model(project_name="Units")
        model.add_material("Steel", E=2.0e11, nu=0.3)
        model.add_rectangular_section("RackSec", height_y=0.1, height_z=0.1, thickness_y=0.01, thickness_z=0.01)
        return model

    def _by_patch(self, factory, params) -> Model:
        model = self._model()
        ModelTransaction(model).apply(factory(**params).to_patch(), validate=True)
        return model

    def _by_unit(self, ref: str, params: dict) -> Model:
        model = self._model()
        assemble(model, ref, **params)
        return model

    def test_rack_bay_unit_matches_the_patch(self):
        direct = self._by_patch(RackBay, BAY_PARAMS)
        assembled = self._by_unit("tuba.assemblies:rack_bay", BAY_PARAMS)

        self.assertTrue(same_model(direct, assembled))
        self.assertEqual([call["ref"] for call in assembled.assembly_calls], ["tuba.assemblies:rack_bay"])

    def test_rack_row_unit_matches_the_patch(self):
        direct = self._by_patch(RackRow, ROW_PARAMS)
        assembled = self._by_unit("tuba.assemblies:rack_row", ROW_PARAMS)

        self.assertTrue(same_model(direct, assembled))
        self.assertEqual(len(assembled.assembly_calls), 1)

    def test_rack_corner_unit_matches_the_patch(self):
        first = dict(ROW_PARAMS)
        corner = dict(name_prefix="rack_B", turn="left", bays=1)

        direct = self._model()
        ModelTransaction(direct).apply(RackCorner(first=RackRow(**first), **corner).to_patch(), validate=True)
        assembled = self._by_unit("tuba.assemblies:rack_corner", {"first": first, **corner})

        self.assertTrue(same_model(direct, assembled))

    def test_generated_script_replays_the_row_as_one_call(self):
        model = self._by_unit("tuba.assemblies:rack_row", ROW_PARAMS)

        with tempfile.TemporaryDirectory() as tmp:
            script = Path(tmp) / "model.py"
            script.write_text(
                '"""Tuba v4 procedural pipeline script generated by Tuba MCP."""\nmodel = None\n',
                encoding="utf-8",
            )
            text = write_model_script(script, model, last_text=script.read_text(encoding="utf-8"))

            self.assertEqual(text.count("assemble(model,"), 1)
            self.assertIn("'tuba.assemblies:rack_row'", text)
            self.assertTrue(same_model(run_model_script(script)["model"], model))


if __name__ == "__main__":
    unittest.main()
