"""Construction units: defs in model.py or units/ replay as assemble() calls."""

from __future__ import annotations

from pathlib import Path

import pytest

from tuba import Model
from tuba.assemblies import assemble
from tuba.project import run_model_script
from tuba.project.script import (
    _prologue_segments,
    generate_model_script,
    same_model,
    write_model_script,
)

POSTS = (
    "def posts(model, x0=0.0, n=2):\n"
    "    for i in range(n):\n"
    "        model.add_node([x0 + float(i), 0.0, 0.0])\n"
)


def _model():
    model = Model(project_name="Units")
    model.add_material("Steel", E=2.0e11, nu=0.3)
    return model


def test_inline_def_is_preserved_and_replayed_as_a_call(tmp_path: Path):
    script = tmp_path / "model.py"
    script.write_text(
        '"""Tuba v4 procedural pipeline script generated by Tuba MCP."""\n\n'
        "from tuba.model import TubaModel\n\n" + POSTS + "\nmodel = TubaModel(project_name='Units')\n",
        encoding="utf-8",
    )
    namespace: dict = {"__name__": "__main__", "__file__": str(script)}
    exec(compile(script.read_text(encoding="utf-8"), str(script), "exec"), namespace)
    model = namespace["model"]
    assemble(model, "posts", _namespace=namespace, x0=5.0, n=2)

    text = write_model_script(script, model, last_text=script.read_text(encoding="utf-8"))
    assert POSTS in text
    assert "assemble(model, 'posts', x0=5.0, n=2)" in text
    assert text.count("from tuba.model import BendGeometry, IBeamSection, TubaModel") == 1

    again = write_model_script(script, run_model_script(script)["model"], last_text=text)
    assert again == text  # stable across reloads
    assert same_model(run_model_script(script)["model"], model)


def test_units_package_import_replays_with_its_import(tmp_path: Path, monkeypatch):
    (tmp_path / "units").mkdir()
    (tmp_path / "units" / "rack.py").write_text(POSTS.replace("def posts", "def posts"), encoding="utf-8")
    monkeypatch.syspath_prepend(str(tmp_path))
    model = _model()
    assemble(model, "units.rack:posts", x0=1.0, n=2)

    script = tmp_path / "model.py"
    script.write_text('"""Tuba v4 procedural pipeline script generated by Tuba MCP."""\nmodel = None\n', encoding="utf-8")
    text = write_model_script(script, model, last_text=script.read_text(encoding="utf-8"))
    # No import is emitted: assemble() resolves 'units.rack:posts' itself at replay.
    assert "assemble(model, 'units.rack:posts', x0=1.0, n=2)" in text
    rebuilt = run_model_script(script)["model"]
    assert same_model(rebuilt, model)
    assert [node.coords[0] for node in rebuilt.nodes.values()] == [1.0, 2.0]


def test_stray_prologue_statements_are_refused_not_dropped(tmp_path: Path):
    script = tmp_path / "model.py"
    script.write_text(
        '"""Tuba v4 procedural pipeline script generated by Tuba MCP."""\n\nSPACING = 2.0\n\nmodel = None\n',
        encoding="utf-8",
    )
    with pytest.raises(ValueError, match="does not preserve"):
        write_model_script(script, _model(), last_text=script.read_text(encoding="utf-8"))
    assert "SPACING" in script.read_text(encoding="utf-8")


def test_nested_units_replay_as_the_outer_call_only(tmp_path: Path):
    model = _model()
    namespace: dict = {}
    exec(POSTS, namespace)

    def outer(m, x0=0.0):
        assemble(m, "posts", _namespace=namespace, x0=x0, n=2)

    namespace["outer"] = outer
    assemble(model, "outer", _namespace=namespace, x0=3.0)
    assert len(model.assembly_calls) == 2

    script = tmp_path / "model.py"
    script.write_text('"""Tuba v4 procedural pipeline script generated by Tuba MCP."""\nmodel = None\n', encoding="utf-8")
    text = generate_model_script(model, prologue=["from x import outer, posts", POSTS])
    assert text.count("assemble(model,") == 1
    assert "'outer'" in text


LINE_UNIT = (
    "def line(m):\n"
    '    with m.pipe(section="DN100", material="Steel") as builder:\n'
    "        builder.start([0.0, 0.0, 0.0])\n"
    "        builder.run(2.0)\n"
    "        builder.end()\n"
)


def test_a_pipe_run_inside_a_unit_is_not_built_twice(tmp_path: Path):
    model = _model()
    model.add_pipe_section("DN100", OD=0.1143, WT=0.00602)

    namespace: dict = {}
    exec(LINE_UNIT, namespace)
    assemble(model, "line", _namespace=namespace)
    assert len(model.pipe_runs) == 1

    script = tmp_path / "model.py"
    script.write_text(
        '"""Tuba v4 procedural pipeline script generated by Tuba MCP."""\n\n' + LINE_UNIT + "\nmodel = None\n",
        encoding="utf-8",
    )
    text = write_model_script(script, model, last_text=script.read_text(encoding="utf-8"))
    assert "assemble(model, 'line')" in text
    assert "with model.pipe" not in text  # the run replays inside the call, not as a block
    assert same_model(run_model_script(script)["model"], model)


def test_an_unresolvable_unit_flattens_to_singles_without_losing_geometry(tmp_path: Path):
    model = _model()
    namespace: dict = {}
    exec(POSTS, namespace)
    assemble(model, "posts", _namespace=namespace, x0=4.0, n=2)

    script = tmp_path / "model.py"
    script.write_text('"""Tuba v4 procedural pipeline script generated by Tuba MCP."""\nmodel = None\n', encoding="utf-8")
    namespace.clear()  # the def is gone: nothing resolves it anymore
    text = write_model_script(script, model, last_text=script.read_text(encoding="utf-8"))
    assert "assemble(" not in text
    rebuilt = run_model_script(script)["model"]
    assert [node.coords[0] for node in rebuilt.nodes.values()] == [4.0, 5.0]


def test_partially_overlapping_spans_are_refused(tmp_path: Path):
    model = _model()
    namespace: dict = {}
    exec(POSTS, namespace)
    assemble(model, "posts", _namespace=namespace, x0=0.0, n=4)
    model.add_support("N0", "anchor")
    # A forged call crossing the recorded spans (nodes inside, supports outside)
    # cannot replay exactly.
    model.assembly_calls.append(
        {"ref": "other", "params": {}, "node0": 1, "element0": 0, "support0": 0,
         "node1": 3, "element1": 0, "support1": 1}
    )
    script = tmp_path / "model.py"
    script.write_text('"""Tuba v4 procedural pipeline script generated by Tuba MCP."""\nmodel = None\n', encoding="utf-8")
    with pytest.raises(ValueError, match="overlap"):
        generate_model_script(model)


def test_a_contained_forgery_is_absorbed_by_the_outer_call(tmp_path: Path):
    model = _model()
    namespace: dict = {}
    exec(POSTS, namespace)
    assemble(model, "posts", _namespace=namespace, x0=0.0, n=4)
    model.assembly_calls.append(
        {"ref": "other", "params": {}, "node0": 1, "element0": 0, "support0": 0,
         "node1": 3, "element1": 0, "support1": 0}
    )
    script = tmp_path / "model.py"
    script.write_text(
        '"""Tuba v4 procedural pipeline script generated by Tuba MCP."""\n\n' + POSTS + "\nmodel = None\n",
        encoding="utf-8",
    )
    text = write_model_script(script, model, last_text=script.read_text(encoding="utf-8"))
    assert text.count("assemble(model,") == 1
    assert [node.coords[0] for node in run_model_script(script)["model"].nodes.values()] == [0.0, 1.0, 2.0, 3.0]


def test_replay_as_main_stamps_imported_records_with_the_call_line(tmp_path: Path, monkeypatch):
    (tmp_path / "units").mkdir()
    (tmp_path / "units" / "rack.py").write_text(POSTS, encoding="utf-8")
    monkeypatch.syspath_prepend(str(tmp_path))
    script = tmp_path / "model.py"
    script.write_text(
        '"""Tuba v4 procedural pipeline script generated by Tuba MCP."""\n\n'
        "from tuba.model import TubaModel\n"
        "from tuba.assemblies import assemble\n"
        "from units.rack import posts\n\n"
        "model = TubaModel(project_name='Units')\n"
        "assemble(model, 'units.rack:posts', x0=0.0, n=1)\n",
        encoding="utf-8",
    )
    model = run_model_script(script)["model"]
    call_line = next(
        index for index, line in enumerate(script.read_text(encoding="utf-8").splitlines(), start=1)
        if line.startswith("assemble(model,")
    )
    assert model.nodes["N0"].source_line == call_line


def test_repeated_steps_replay_as_a_loop(tmp_path: Path):
    model = _model()
    model.add_pipe_section("DN100", OD=0.1143, WT=0.00602)
    with model.pipe(section="DN100", material="Steel") as builder:
        builder.start([0.0, 0.0, 0.0], support="anchor")
        for _ in range(5):
            builder.run(2.0)
        builder.end(support="anchor")

    script = tmp_path / "model.py"
    script.write_text('"""Tuba v4 procedural pipeline script generated by Tuba MCP."""\nmodel = None\n', encoding="utf-8")
    text = write_model_script(script, model, last_text=script.read_text(encoding="utf-8"))
    assert "    for _ in range(5):\n        builder.run(2.0)" in text
    assert same_model(run_model_script(script)["model"], model)


def test_pairs_of_steps_stay_unrolled(tmp_path: Path):
    model = _model()
    model.add_pipe_section("DN100", OD=0.1143, WT=0.00602)
    with model.pipe(section="DN100", material="Steel") as builder:
        builder.start([0.0, 0.0, 0.0], support="anchor")
        builder.run(2.0)
        builder.run(2.0)
        builder.end(support="anchor")

    script = tmp_path / "model.py"
    script.write_text('"""Tuba v4 procedural pipeline script generated by Tuba MCP."""\nmodel = None\n', encoding="utf-8")
    text = write_model_script(script, model, last_text=script.read_text(encoding="utf-8"))
    assert "for _ in range" not in text
    assert same_model(run_model_script(script)["model"], model)


def test_invocation_call_carries_a_summary_of_what_it_builds(tmp_path: Path):
    model = _model()
    namespace: dict = {}
    exec(POSTS, namespace)
    assemble(model, "posts", _namespace=namespace, x0=0.0, n=2)
    model.add_support("N0", "anchor")

    script = tmp_path / "model.py"
    script.write_text(
        '"""Tuba v4 procedural pipeline script generated by Tuba MCP."""\n\n' + POSTS + "\nmodel = None\n",
        encoding="utf-8",
    )
    text = write_model_script(script, model, last_text=script.read_text(encoding="utf-8"))
    assert "# posts: 2 nodes, 0 elements, 0 supports" in text


def test_invocation_record_shape_is_owned_by_script():
    import tuba.assemblies
    import tuba.mcp.server
    import tuba.project.script as script

    for name in ("call_span", "format_call", "owned_records", "range_skipped"):
        assert callable(getattr(script, name)), name
        assert not hasattr(tuba.assemblies, name), name
    for name in ("prologue_namespace", "project_on_path"):
        assert callable(getattr(script, name)), name
    assert not hasattr(tuba.mcp.server, "_prologue_namespace")
    assert not hasattr(tuba.mcp.server, "_project_on_path")


def test_prologue_segments_ignores_the_header_and_keeps_order():
    text = (
        '"""Tuba v4 procedural pipeline script generated by Tuba MCP."""\n\n'
        "import os\nfrom units.rack import posts\n\n"
        "def helper(model):\n    pass\n\n"
        "model = TubaModel(project_name='X')\n"
    )
    assert _prologue_segments(text) == ["import os", "from units.rack import posts", "def helper(model):\n    pass"]
    assert _prologue_segments(None) == []
