"""Generated model scripts: the ``model.py`` an authoring session writes for its model.

A generated model script starts with ``GENERATED_HEADER``; any other script is authored,
and tools read it but never rewrite it. A generated script makes one public call per
record where a call reproduces the record exactly, so every element and support links to
its own line in the studio, and writes literals for the rest (groups, specs other than
insulation, I-beam properties). Running it rebuilds a model that serialises to the same
JSON text as the model it was generated from.
"""

from __future__ import annotations

import json
import math
from dataclasses import fields
from pathlib import Path
from typing import Any

import numpy as np

from tuba.model import BarSection, CableSection, IBeamSection, PipeSection, RectangularSection, TubaModel
from tuba.refs import EntityRef

GENERATED_HEADER = '"""Tuba v4 procedural pipeline script generated by Tuba MCP."""'


class AuthoredModelScript(ValueError):
    """The file holds an authored model script, which tools never rewrite."""


class ModelScriptChanged(RuntimeError):
    """The file changed since it was last read or written, so writing over it would lose that edit."""


def is_generated(text: str) -> bool:
    """Whether *text* is a generated model script; a leading byte-order mark is ignored."""
    return text.lstrip("\ufeff").startswith(GENERATED_HEADER)


def same_model(first: TubaModel, second: TubaModel) -> bool:
    """Whether two models serialise to the same JSON text, key order included."""
    return _json_text(first) == _json_text(second)


def generate_model_script(model: TubaModel) -> str:
    """The generated model script that rebuilds *model*."""
    from tuba.attributes import InsulationSpec

    node_ids = list(model.nodes)
    if node_ids != [f"N{index}" for index in range(len(node_ids))]:
        raise ValueError(
            "A generated model script writes nodes as add_node calls, which number them N0, N1, ... in order; "
            "this model's node ids are not in that sequence."
        )
    data = model.to_dict()
    lines = [
        GENERATED_HEADER,
        "",
        "from tuba.model import BendGeometry, IBeamSection, TubaModel",
        "from tuba.placements import PlacementAssignment, PlacementFrame",
        "",
        f"model = TubaModel(project_name={_literal(model.project_name)}, standard={_literal(model.standard)})",
    ]
    for name, material in model.materials.items():
        lines.append(
            f"model.add_material({_literal(name)}, E={_literal(material.E)}, nu={_literal(material.nu)}, "
            f"rho={_literal(material.rho)}, alpha={_literal(material.alpha)}, "
            f"allowable_stress={_literal(dict(material.allowable_stress))})"
        )
    for name, section in model.sections.items():
        lines.append(_section_line(name, section))
    for node in model.nodes.values():
        lines.append(f"model.add_node({_literal(node.coords.tolist())})")
    for element in data["elements"]:
        lines.append(_element_line(element))
    for support in data["supports"]:
        lines.append(f"model.add_support({_keywords(support)})")
    for name, case in model.load_cases.items():
        lines.append(
            f"model.define_load_case({_literal(name)}, gravity={_literal(case.gravity)}, "
            f"pressure={_literal(case.internal_pressure)}, temperature={_literal(case.temperature)}, "
            f"ref_temperature={_literal(case.ref_temperature)})"
        )
        for force in case.nodal_forces:
            lines.append(
                f"model.load_cases[{_literal(name)}].add_nodal_force({_literal(force.node)}, {_literal(force.components)})"
            )
    for name, operation in model.operations.items():
        lines.append(
            f"model.define_operation({_literal(name)}, gravity={_literal(operation.gravity)}, "
            f"pressure={_literal(operation.internal_pressure)}, temperature={_literal(operation.temperature)}, "
            f"ref_temperature={_literal(operation.ref_temperature)}, metadata={_literal(operation.metadata)}, "
            f"fields={_literal(data['operations'][name]['fields'])})"
        )
        for force in operation.nodal_forces:
            lines.append(
                f"model.operations[{_literal(name)}].add_nodal_force({_literal(force.node)}, {_literal(force.components)})"
            )
    for node_id, tee in model.tees.items():
        lines.append(
            f"model.define_tee({_literal(node_id)}, type={_literal(tee.type)}, pad_thickness={_literal(tee.pad_thickness)})"
        )
    for obstacle in model.obstacles:
        lines.append(f"model.add_obstacle({_keywords(obstacle)})")
    # No public call reproduces every group exactly (patch-created groups gain keys), so groups are literals.
    for name, group in model.groups.items():
        lines.append(f"model.groups[{_literal(name)}] = {_literal(group)}")
    for frame in model.placement_frames.values():
        lines.append(f"model.add_placement_frame(PlacementFrame({_record_keywords(frame)}))")
    for assignment in model.placement_assignments:
        lines.append(f"model.assign_placement(PlacementAssignment({_record_keywords(assignment)}))")
    for kind, entries in model.specs.items():
        if kind == "insulation" and entries and all(isinstance(spec, InsulationSpec) for spec in entries.values()):
            lines.extend(f"model.add_insulation_spec({_record_keywords(spec)})" for spec in entries.values())
        else:
            lines.append(f"model.specs[{_literal(kind)}] = {_literal(dict(entries))}")
    for assignment in model.attributes:
        lines.append(
            f"model.assign_attribute({_literal(str(assignment.target))}, {_literal(assignment.key)}, "
            f"{_literal(assignment.value)}, source={_literal(assignment.source)}, metadata={_literal(assignment.metadata)})"
        )
    for method, records in (
        ("add_cad_asset", model.cad_assets),
        ("add_imported_component", model.imported_components),
        ("add_analysis_region", model.analysis_regions),
        ("add_port", model.ports),
        ("add_mesh_group", model.mesh_groups),
        ("add_coupling", model.couplings),
    ):
        lines.extend(f"model.{method}({_record_keywords(record)})" for record in records.values())
    return "\n".join(lines) + "\n"


def write_model_script(path: str | Path, model: TubaModel, *, last_text: str | None) -> str:
    """Write the generated script for *model* to *path* and return the text written.

    *last_text* is the text this caller last read from, or wrote to, *path* (None when the
    file did not exist), as ``Path.read_text(encoding="utf-8")`` returns it or as this
    function returned it. Nothing is written when the file holds an authored script, when it
    changed since *last_text*, or when running the generated text does not rebuild *model*.
    """
    target = Path(path)
    _check_rewritable(target, last_text)
    text = generate_model_script(model)
    namespace: dict[str, Any] = {"__name__": "tuba_generated_model_check"}  # not __main__: no source lines needed
    exec(compile(text, "<generated model script>", "exec"), namespace)
    if not same_model(model, namespace["model"]):
        raise ValueError(f"The generated script for {target} does not rebuild the model exactly, so it was not written.")
    # Check again: the proof takes time, and an editor may have saved the file meanwhile.
    _check_rewritable(target, last_text)
    target.parent.mkdir(parents=True, exist_ok=True)
    # ponytail: written in place, not via a temporary file and os.replace: on Windows a replace can collide
    # with the studio watcher's periodic reads of model.py, and the watcher stops on that sharing violation
    # (_file_fingerprint catches only FileNotFoundError), while a read of a half-written file just reruns once
    # the write completes. Ceiling: a process killed mid-write leaves a truncated model.py. Switch to
    # os.replace with short retries once the watcher tolerates sharing violations.
    target.write_text(text, encoding="utf-8", newline="")
    return text


def _check_rewritable(target: Path, last_text: str | None) -> None:
    current = target.read_text(encoding="utf-8") if target.exists() else None
    if current is not None and not is_generated(current):
        raise AuthoredModelScript(f"{target} is an authored model script, which tools never rewrite.")
    if current != last_text:
        raise ModelScriptChanged(f"{target} changed since it was last read or written, so this change was not saved.")


def _section_line(name: str, section: Any) -> str:
    kind = type(section)
    if kind is PipeSection:
        return (
            f"model.add_pipe_section({_literal(name)}, OD={_literal(section.OD)}, WT={_literal(section.WT)}, "
            f"corrosion_allowance={_literal(section.corrosion_allowance)})"
        )
    if kind is BarSection:
        return f"model.add_bar_section({_literal(name)}, OD={_literal(section.OD)}, WT={_literal(section.WT)})"
    if kind is CableSection:
        return (
            f"model.add_cable_section({_literal(name)}, radius={_literal(section.radius)}, "
            f"pretension={_literal(section.pretension)}, "
            f"compression_modulus_ratio={_literal(section.compression_modulus_ratio)})"
        )
    if kind is RectangularSection:
        return (
            f"model.add_rectangular_section({_literal(name)}, height_y={_literal(section.height_y)}, "
            f"height_z={_literal(section.height_z)}, thickness_y={_literal(section.thickness_y)}, "
            f"thickness_z={_literal(section.thickness_z)})"
        )
    if kind is IBeamSection:
        # Literal properties, not add_ibeam_section: a later profile-catalog change must not change this model.
        return (
            f"model.sections[{_literal(name)}] = IBeamSection(name={_literal(name)}, "
            f"profile_name={_literal(section.profile_name)}, properties={_literal(dict(section.properties))})"
        )
    raise TypeError(f"A generated model script cannot write a {kind.__name__} section.")


def _element_line(element: dict[str, Any]) -> str:
    record = dict(element)  # to_dict() can hand out live objects; never mutate them
    geometry = record.pop("bend_geometry", None)
    text = _keywords(record)
    if geometry is not None:
        text += f", bend_geometry=BendGeometry({_keywords(geometry)})"
    return f"model.add_element({text})"


def _keywords(record: dict[str, Any]) -> str:
    return ", ".join(f"{key}={_literal(value)}" for key, value in record.items())


def _record_keywords(record: Any) -> str:
    return ", ".join(f"{item.name}={_literal(getattr(record, item.name))}" for item in fields(record))


def _literal(value: Any) -> str:
    """Python source that evaluates to *value*: floats by repr, NaN and infinity spelled out, tuples kept."""
    kind = type(value)
    if value is None or kind in (bool, int, str):
        return repr(value)
    if kind is float or isinstance(value, np.floating):
        number = float(value)  # repr(np.float64) is "np.float64(...)", which is not valid here
        if math.isnan(number):
            return 'float("nan")'
        if math.isinf(number):
            return 'float("inf")' if number > 0 else 'float("-inf")'
        return repr(number)
    if isinstance(value, np.integer):
        return repr(int(value))
    if isinstance(value, np.bool_):
        return repr(bool(value))
    if kind is list:
        return "[" + ", ".join(_literal(item) for item in value) + "]"
    if kind is tuple:
        return "(" + ", ".join(_literal(item) for item in value) + ("," if len(value) == 1 else "") + ")"
    if kind is dict:
        return "{" + ", ".join(f"{_literal(key)}: {_literal(item)}" for key, item in value.items()) + "}"
    if isinstance(value, EntityRef):
        return repr(str(value))
    raise TypeError(f"A generated model script cannot write a {kind.__name__} value.")


def _json_text(model: TubaModel) -> str:
    return json.dumps(model.to_dict(), default=_plain)


def _plain(value: Any) -> Any:
    if hasattr(value, "tolist"):  # numpy scalars and arrays
        return value.tolist()
    raise TypeError(f"{type(value).__name__} is not JSON serializable")
